# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Practice and theory of brain imaging
author: The nipraxis team
# >- starts a multiline string, where newlines replaced by spaces, and final
# newlines are stripped.
description: >-
  Textbook for Practice and Theory of Brain Imaging course.
  https://nipraxis.org for more information on the course.

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # 'cache' attempts to cache the results.
  # 'auto' appears to be safer.
  execute_notebooks: auto
  timeout: 120

exclude_patterns:
  # Remove pages from this list as they are fixed.
  # When removing, if the pages aren't in the toctree,
  # add orphan: true to YaML frontmatter, e.g. syllabus.md.
  # https://myst-parser.readthedocs.io/en/latest/sphinx/use.html#sphinx-specific-page-front-matter
  # Notebooks need this key/value to be in the `jupyter` YaML section, e.g
  # string_formatting.Rmd.
  # https://github.com/executablebooks/meta/discussions/105
  # https://myst-nb.readthedocs.io/en/latest/use/orphaned_nb.html#orphaned-nb
  # OE: I have sorted the pages with a tentative sectioning
  #
  # Python and Numpy
  - comparing_arrays.Rmd
  - comparing_floats.md
  - diag_inverse.md
  - dot_and_outer.md
  - index_reshape.Rmd
  - keyword_arguments.Rmd
  - numpy_diag.Rmd
  - numpy_meshgrid.Rmd
  - numpy_squeeze.Rmd
  - numpy_transpose.Rmd
  - on_loops.Rmd
  - packages_namespaces.Rmd
  - printing_floating.Rmd
  - subtract_mean_math.md
  # Images and code and images
  - saving_images.Rmd
  # Coordinate systems and spatial transforms
  # [all transferred already]
  # Into the fourth dimension
  - tr_and_headers.Rmd
  # Statistics
  - pearson_functions.md
  - validate_against_scipy.Rmd
  # Code organization and collaboration
  - full_scripting.md
  - git_videos.md
  - git_walk_through.Rmd
  - git_workflow_exercises.md
  - github_dummies_homework.md
  - github_glm_homework.md
  - github_pca_homework.md
  # Meta-course
  - README.md
  - data/README.md
  - _todo.md
  - _scripts
  - bibliography.md
  - classes.md
  - classes_and_labs.md
  - ds114_sub009_highres.nii
  - example_data.md
  - exercises.md
  - glossary.md
  - index.md
  - logistics.md
  - mentors.md
  - multi_model_homework.md
  - participate.md
  - participate_grading.md
  - preparation.md
  - project_grading.md
  - projects.md
  - topics.md
  # Generated by page build.
  - .pytest_cache/*

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: nipraxis.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

html:
  # favicon: images/dsfe_favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://textbook.nipraxis.org

repository:
  url: https://github.com/nipraxis/textbook
  branch: main

launch_buttons:
  # The interface interactive links will activate ["classic", "jupyterlab"]
  notebook_interface: "classic"
  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  jupyterhub_url: "https://hub.nipraxis.org"
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://mybinder.org"
  # The URL of Google Colab (e.g., https://colab.research.google.com)
  colab_url: "https://colab.research.google.com"
  # Deepnote
  deepnote_url: "https://deepnote.com"
  thebe: true

sphinx:
  config:
    html_theme_options:
      logo:
        image_light: images/reggie.png
        image_dark: images/reggie-inv.png
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# HTML redirection
# Pages linked, but then renamed.
redirection:
  builddir : _build/html
  redirects: {}
#   data-types/Ranges: ../arrays/Ranges
#
bibtex_bibfiles:
  - bib/course_refs.bib
