# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Practical Neuroimaging
author: The nipraxis team
logo: images/reggie.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # 'cache' attempts to cache the results.
  # 'auto' appears to be safer.
  execute_notebooks: auto
  timeout: 120

exclude_patterns: [README.md, todo.md, _scripts, _to_port]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: nipraxis.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

html:
  # favicon: images/dsfe_favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://nipraxis.github.io

repository:
  url: https://github.com/nipraxis/nipraxis.github.io
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# HTML redirection
# Pages linked, but then renamed.
redirection:
  builddir : _build/html
# redirects:
#   data-types/Ranges: ../arrays/Ranges
