# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Practical Neuroimaging
author: The nipraxis team
logo: images/reggie.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # 'cache' attempts to cache the results.
  # 'auto' appears to be safer.
  execute_notebooks: auto
  timeout: 120

exclude_patterns:
  # Remove pages from this list as they are fixed.
  # When removing, if the pages aren't in the toctree,
  # add orphan: true to YaML frontmatter, e.g. syllabus.md.
  # https://myst-parser.readthedocs.io/en/latest/sphinx/use.html#sphinx-specific-page-front-matter
  # Notebooks need this key/value to be in the `jupyter` YaML section, e.g
  # string_formatting.Rmd.
  # https://github.com/executablebooks/meta/discussions/105
  # https://myst-nb.readthedocs.io/en/latest/use/orphaned_nb.html#orphaned-nb
  # OE: I have sorted the pages with a tentative sectioning
  #
  # Python and Numpy
  - pages/boolean_indexing.Rmd
  - pages/array_reductions.md
  - pages/comparing_arrays.Rmd
  - pages/comparing_floats.md
  - pages/diag_inverse.md
  - pages/dot_and_outer.md
  - pages/floating_in_text.md
  - pages/index_reshape.Rmd
  - pages/keyword_arguments.Rmd
  - pages/nans.md
  - pages/numpy_diag.Rmd
  - pages/numpy_meshgrid.Rmd
  - pages/numpy_random.Rmd
  - pages/numpy_squeeze.Rmd
  - pages/numpy_transpose.Rmd
  - pages/on_loops.Rmd
  - pages/packages_namespaces.Rmd
  - pages/printing_floating.Rmd
  - pages/subtract_mean_math.md
  - pages/two_dunders.md
  # Images and code and images
  - pages/saving_images.Rmd
  # Coordinate systems and spatial transforms
  # [all transferred already]
  # Into the fourth dimension
  - pages/tr_and_headers.Rmd
  # Statistics
  - pages/pearson_functions.md
  - pages/validate_against_scipy.Rmd
  # Hemodynamic response modeling
  - pages/anterior_cingulate.md
  - pages/introducing_nipype.Rmd
  # Code organization and collaboration
  - pages/choosing_editor.md
  - pages/full_scripting.md
  - pages/git_videos.md
  - pages/git_walk_through.Rmd
  - pages/git_workflow_exercises.md
  - pages/github_dummies_homework.md
  - pages/github_glm_homework.md
  - pages/github_pca_homework.md
  - pages/installation_on_linux.md
  - pages/installation_on_mac.md
  - pages/installation_on_windows.md
  # Meta-course
  - README.md
  - _todo.md
  - _scripts
  - pages/bibliography.md
  - pages/classes.md
  - pages/classes_and_labs.md
  - pages/diagnostics_project.md
  - pages/ds114_sub009_highres.nii
  - pages/example_data.md
  - pages/exercises.md
  - pages/glossary.md
  - pages/index.md
  - pages/logistics.md
  - pages/markdown.md
  - pages/mentors.md
  - pages/multi_model_homework.md
  - pages/participate.md
  - pages/participate_grading.md
  - pages/preparation.md
  - pages/project_grading.md
  - pages/projects.md
  - pages/topics.md
  # Drop?
  - pages/using_pythonpath.Rmd

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: nipraxis.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

html:
  # favicon: images/dsfe_favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://textbook.nipraxis.org

repository:
  url: https://github.com/nipraxis/textbook
  branch: main

launch_buttons:
  # The interface interactive links will activate ["classic", "jupyterlab"]
  notebook_interface: "classic"
  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  jupyterhub_url: "https://hub.nipraxis.org"
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://mybinder.org"
  # The URL of Google Colab (e.g., https://colab.research.google.com)
  colab_url: "https://colab.research.google.com"
  # Deepnote
  deepnote_url: "https://deepnote.com"
  thebe: true

sphinx:
  config:
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# HTML redirection
# Pages linked, but then renamed.
redirection:
  builddir : _build/html
# redirects:
#   data-types/Ranges: ../arrays/Ranges
#
bibtex_bibfiles:
  - _references.bib
